version: '2'
services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
  worker:
    build:
      context: .
      dockerfile: Dockerfile-celery-worker
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - rabbit
  producer:
    build:
      context: .
      dockerfile: Dockerfile-celery-producer
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - rabbit
      - worker
  mongo:
    hostname: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
